base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('quiz.urls') ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', views.index, name="index"), 
    path('lesson', views.lesson, name="lesson"), 
    path('fact', views.fact, name="fact"), 
    path('quizes', views.quizes, name="quizes"), 
    path('login', views.login_view, name="login"), 
    path('register', views.register_view, name="register"), 
    path('contact', views.contact, name="contact"), 
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),

          path(
        'forgot-password/',
        auth_views.PasswordResetView.as_view(
            template_name='quiz/forgot-password.html',
            email_template_name='quiz/password_reset_email.html',
            subject_template_name='quiz/password_reset_subject.txt',
            success_url='/forgot-password/done/'
        ),
        name='password_reset'
    ),

    # Email sent page
    path(
        'forgot-password/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='quiz/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    # Link from email (enter new password)
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='quiz/password_reset_confirm.html',
            success_url='/reset/done/'
        ),
        name='password_reset_confirm'
    ),

    # Success page
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='quiz/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    school = models.CharField(max_length=255)
 

    def __str__(self):
        return self.user.username
    


class Home(models.Model) : 
    heading = models.CharField(max_length=180)
    text = models.TextField() 
    title = models.CharField(max_length=180)
    decription = models.TextField() 
    btn_text =  models.CharField(max_length=60)

    def __str__(self):
        return self.heading
           


class ScratcLesson(models.Model):
    heading = models.CharField(max_length=255, null=True,blank=True)
    text = models.TextField(null=True,blank=True)
    title = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return self.title


class ScratchCourse(models.Model):
    title = models.CharField(max_length=255,null=True,blank=True)
    text = models.TextField(null=True,blank=True)
    btn_text = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return f"{self.title}"



class LessonContent(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()  
    quiz = models.JSONField(default=list)

    def __str__(self):
        return self.title
    


class Fact(models.Model):
    title = models.CharField(max_length=180)
    heading = models.CharField(max_length=190)
    description = models.TextField()

    def __str__(self):
        return self.title
    
class AllScratchFacts(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField()

    def __str__(self):
        return self.title
    


class Quiz(models.Model):
    heading = models.CharField(max_length=40)
    title = models.CharField(max_length=80)
    descrption = models.TextField()
    
    def __str__(self):
        return self.heading
    



class QuizLevel(models.Model):
    name = models.CharField(max_length=20)  # level1, level2

    def __str__(self):
        return self.name


class QuizQuestion(models.Model):
    level = models.ForeignKey(
        QuizLevel,
        on_delete=models.CASCADE,
        related_name="questions"
    )
    question = models.TextField()
    option1 = models.CharField(max_length=255)
    option2 = models.CharField(max_length=255)
    option3 = models.CharField(max_length=255)
    correct_answer = models.IntegerField()  # 0,1,2
    hint = models.TextField()

    def __str__(self):
        return self.question[:50]

quiz/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.models import User
import json
from .models import (
     Home,ScratcLesson,ScratchCourse,LessonContent,
     Fact,AllScratchFacts,QuizLevel
     )
from .form import RegisterForm
# Create your views here.



def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Գրանցումը հաջողությամբ կատարվեց։")
            return redirect("login")  # կամ "home"
    else:
        form = RegisterForm()

    return render(request, "quiz/register.html", {"form": form})



def index(request):
    home = Home.objects.first()
    return render(request, "quiz/index.html",{'home': home})


def lesson(request):
    less = ScratcLesson.objects.first()
    course = ScratchCourse.objects.all()
    lessonContent = LessonContent.objects.all()

    lessons_dict = {}
    for l in lessonContent:
        lessons_dict[str(l.id)] = {
            'title': l.title,
            'content': l.content,
            'quiz': l.quiz
        }

    return render(request, "quiz/lessons.html", {
        "less": less,
        "course": course,
        "lessonContent": lessons_dict,  
    })



def fact(request):
    fact = Fact.objects.first()

    allScratchFacts_qs = AllScratchFacts.objects.all()

    allScratchFacts = []
    for f in allScratchFacts_qs:
        allScratchFacts.append({
            "id": f.id,
            "title": f.title,
            "text": f.text,
        })

    return render(request, "quiz/fact.html", {
        "fact": fact,
        "allScratchFacts": allScratchFacts, 
    })


def quizes(request):
    quiz = {
        "heading": "Scratch Quizes",
        "title": ">Մտքի Բլոկ",
        "descrption": "Մենք օգնում ենք երեխաներին և սկսնակներին բացահայտել իրենց երևակայությունը, սովորել մտածել ճիշտ և ստեղծել ուրախ խաղեր ու անիմացիաներ, աջակցում ենք ՝ զարգացնելու իրենց երևակայությունը, մտածողությունը և ինքնավստահությունը՝ Scratch-ում ստեղծելով խաղեր և անիմացիաներ"
    }
    quizData = {}

    levels = QuizLevel.objects.prefetch_related("questions")

    for level in levels:
            quizData[level.name] = []

            for q in level.questions.all():
                quizData[level.name].append({
                    "q": q.question,
                    "options": [q.option1, q.option2, q.option3],
                    "answer": q.correct_answer,
                    "hint": q.hint
                })
    return render(request, "quiz/quizes.html", {'quizData': quizData, 'quiz': quiz})


def login_view(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.error(request, "Էլ․ հասցե կամ գաղտնաբառ սխալ է։")
            return redirect("login")

        user = authenticate(username=user.username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            messages.error(request, "Էլ․ հասցե կամ գաղտնաբառ սխալ է։")
            return redirect("login")

    return render(request, "quiz/login.html")

def contact(request):
    contact = {
        "heading": "Կապ մեզ հետ",
        "descr": "Ուղարկիր մեզ հաղորդագրություն, և մենք կպատասխանենք հնարավորինս շուտ։",
        "contact_btn": "ՈւՂԱՐԿԵԼ ՆԱՄԱԿ"
    }
    
    return render(request, 'quiz/contact.html', {'contact': contact})

quiz/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="hy">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome and Google Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" 
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Armenian:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- Your CSS -->
    <link rel="stylesheet" href="{% static 'quiz/css/index.css' %}">
     {% block extra_css %}{% endblock %}
    <title>Մտքի Բլոկ | Scratch Ծրագրավորման Դասեր</title>
</head>

<body>

    <header>
        <div class="logo">
            <a href="#">
                <img src="{% static 'quiz/images/image2.png' %}" alt="/">
            </a>
        </div>

        <nav>
            <ul class="menu">
                <li><a href="{% url "index" %}">Գլխավոր</a></li>
                <li><a href="{% url "lesson" %}">Դասեր</a></li>
                <li><a href="{% url "fact" %}">Հետաքրքիր փաստեր</a></li>
                <li><a href="{% url "quizes" %}">Quizes</a></li>

                <li class="dropdown">
                   {% if request.user.is_authenticated %}
        <a href="#">{{ request.user.username }}</a>
        <ul class="drop_content">
          <li>
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" style="all:unset; cursor:pointer;">Դուրս Գալ</button>
            </form>
          </li>
        </ul>
      {% else %}
        <a href="{% url "contact" %}">Կապ մեզ հետ</a>
          <li><a href="{% url 'login' %}">Մուտք</a></li>
          <li><a href="{% url 'register' %}">Գրանցվել</a></li>
      {% endif %}
                </li>
            </ul>
        </nav>
    </header>


{% block content %}

{% endblock  %}
    <footer>
        <p>© 2025 Մտքի Բլոկ. Բոլոր իրավունքները պաշտպանված են:</p>
    </footer>

 {% block scripts %}{% endblock  %}
   
</body>

</html>    

quiz/templates/quiz/contact.html
{% extends "base.html" %}
{% load static %}

    {% block extra_css %}
    <link rel="stylesheet" href="{% static "quiz/css/contact.css" %}" />
{% endblock %}


{% block content %}

    <section class="contact-section">
      <div class="wrapper">
        <h1>{{contact.heading}}</h1>
        <p>{{contact.descr}}</p>
   <div class="auth-boxes">
       <div class="auth-card">
        <form >
          <input type="text" name="name" placeholder="Անուն" required />
          <input type="email" name="email" placeholder="Էլ․ հասցե" required />
          <input type="text" name="subject" placeholder="Թեմա" required />
          <textarea name="message" placeholder="Հաղորդագրություն" rows="4" required></textarea>
          <button type="submit" class="btn primary">{{contact.contact_btn}}</button>
        </form>
      </div>
    </div></div>
    </section>

{% endblock  %}

{% block scripts %}
<script>
document.addEventListener("DOMContentLoaded", function() {
  const form = document.querySelector(".contact-form");

  form.addEventListener("submit", function(e) {
    e.preventDefault(); // կանխում է իրական submit-ը

    
    const name = form.name.value.trim();
    const email = form.email.value.trim();
    const subject = form.subject.value.trim();
    const message = form.message.value.trim();

    const exampleEmail = "example@example.com";
   
    alert(
      `Հաղորդագրություն ուղարկվել է:\n\nTo: ${exampleEmail}\nԱնուն: ${name}\nԷլ․ հասցե: ${email}\nԹեմա: ${subject}\nՀաղորդագրություն: ${message}`
    );

    form.reset();
  });
});
</script>
  <script src="{% static "quiz/js/header.js" %}"></script>
{% endblock  %}

quiz/templates/quiz/fact.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'quiz/css/fact.css' %}">
{% endblock %}


{% block content %}
{{ allScratchFacts|json_script:"all-facts-data" }}
    <main>
        <section id="facts" class="facts-container">
            <h2 class="fact-title">{{fact.title}}</h2>

            <div id="facts-container-grid" class="fun-facts-grid">
            </div>

        </section>
        <section id="about">
            <div class="about_container">
                <div class="content_block">
                    <img src="{% static 'quiz/images/image.png' %}" alt="s">
                    <div class="content">
                       <h2>{{fact.heading}}</h2>
                        <p>{{fact.description}}</p>
                    </div>
                </div>
                <img class="one" src="{% static "quiz/images/Scratchlogo.png" %}" alt="s">
            </div>
        </section>
    </main>
{% endblock  %}
{% block scripts %}
    <script>
      const allScratchFacts = JSON.parse(document.getElementById("all-facts-data").textContent);


        function getRandomFacts(arr, num) {
            const shuffled = [...arr].sort(() => 0.5 - Math.random());
            return shuffled.slice(0, num);
        }

        function displayRandomFacts() {
            const gridContainer = document.getElementById('facts-container-grid');
            const selectedFacts = getRandomFacts(allScratchFacts, 6); 

            let htmlContent = '';

            selectedFacts.forEach(fact => {
                const titleWithEmojiSpan = fact.title.replace(/([\uD800-\uDBFF][\uDC00-\uDFFF]|\s)*/, (match, p1) => `<span style="font-size: 2.5em; vertical-align: middle; margin-right: 5px; line-height: 1;">${match.trim()}</span> `);

                htmlContent += `
                    <div class="fact-card">
                        <h4>${fact.title}</h4>
                        <p>${fact.text}</p>
                    </div>
                `;
            });

            const regex = /^(\S+)\s/; 

            let newHtmlContent = '';
            selectedFacts.forEach(fact => {
                const emojiMatch = fact.title.match(regex);
                let formattedTitle;

                if (emojiMatch) {
                    const emoji = emojiMatch[1]; 
                    const restOfTitle = fact.title.substring(emojiMatch[0].length);
                    formattedTitle = `<span style="font-size: 2.5em; vertical-align: middle; margin-right: 5px; line-height: 1;">${emoji}</span>${restOfTitle}`;
                } else {
                    formattedTitle = fact.title;
                }

                newHtmlContent += `
                    <div class="fact-card">
                        <h4>${formattedTitle}</h4>
                        <p>${fact.text}</p>
                    </div>
                `;
            });

            gridContainer.innerHTML = newHtmlContent;
        }
        window.onload = displayRandomFacts;
    </script>
{% endblock  %}
       

quiz/templates/quiz/forgot-password.html
{% extends "base.html" %} 
{% load static %}
 {% block extra_css %}
<link rel="stylesheet" href="{% static 'quiz/css/forgot-password.css' %}" />
{% endblock %} 

{% block content %}
<main>
  <div class="confirm-container">
    <div class="logo">
      <img class="img" src="{% static 'quiz/images/image1.png' %}" alt="" />
      <h2>Մոռացել եք գաղտնաբառը՞</h2>
      <img
        class="text"
        src="{% static 'quiz/images/Scratchlogo.png' %}"
        alt="s"
      />
    </div>
<form method="POST">
    {% csrf_token %}

    {{ form.email.label_tag }}
    {{ form.email }}
    {{ form.email.errors }}

    <button type="submit">
        Ուղարկել վերականգնման հղումը
    </button>
</form>

  </div>
</main>
{% endblock %} 

quiz/templates/quiz/header.html
   {% extends "base.html" %}
   {% load static %}
<!DOCTYPE html>
<html lang="hy">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome and Google Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" 
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Armenian:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- Your CSS -->
    <link rel="stylesheet" href="{% static 'quiz/css/index.css' %}">
     {% block extra_css %}{% endblock %}
    <title>Մտքի Բլոկ | Scratch Ծրագրավորման Դասեր</title>
</head>

<body>
   <header>
        <div class="logo">
            <a href="#">
                <img src="{% static 'quiz/images/image2.png' %}" alt="/">
            </a>
        </div>

        <nav>
            <ul class="menu">
                <li><a href="{% url "index" %}">Գլխավոր</a></li>
                <li><a href="{% url "lesson" %}">Դասեր</a></li>
                <li><a href="{% url "fact" %}">Հետաքրքիր փաստեր</a></li>
                <li><a href="{% url "quizes" %}">Quizes</a></li>
                    <a href="{% url "contact" %}">Կապ մեզ հետ</a>
                        <li><a href="{% url "login" %}">Մուտք</a></li>
                        <li><a href="{% url "register" %}">Գրանցվել</a></li>
            </ul>
        </nav>
    </header>
</body>

</html>    

quiz/templates/quiz/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <main>
        <section id="home" class="hero">
            <h1 class="hero-title">{{home.heading}}</h1>
            <p>{{home.text}}</p>
            <img src="{% static "quiz/images/image1.png" %}" alt="i">
            <a href="{% url "lesson" %}" class="btn-start">{{home.btn_text}}</a>

            <!-- Chevron arrow -->
            <a class="scroll-down" href="#about">
                <i class="chevron bottom"></i>
            </a>
        </section>

        <section id="about">
            <div class="about_container">
                <div class="content_block">
                    <img src="{% static "quiz/images/image.png" %}" alt="s">
                    <div class="content">
                        <h2>{{home.title}}</h2>
                        <p>{{home.decription}}</p>

                    </div>
                </div>
                <img class="one" src="{% static 'quiz/images/Scratchlogo.png' %}" alt="s">
            </div>
        </section>
    </main>
{% endblock  %}

{% block scripts %}
 <script>
        const title = document.querySelector(".hero-title");
        const text = title.innerText;

        title.innerHTML = "";

        [...text].forEach((char, index) => {
            const span = document.createElement("span");
            span.textContent = char === " " ? "\u00A0" : char;
            span.style.animationDelay = `${index * 0.06}s`;
            title.appendChild(span);
        });

    </script>
{% endblock  %}

quiz/templates/quiz/lessons.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'quiz/css/lessons.css' %}">
{% endblock %}


{% block content %}

{{ lessonContent|json_script:"lesson-data" }}
  <main>
  
      <div  class="about_container">

        <div class="content_block">
          <img src="{% static 'quiz/images/image.png' %}" alt="s">
          <div class="content">
            <h2>{{less.heading}}</h2>
            <p>{{less.text}}</p>

          </div>
        </div>
      </div>
  
    <section id="lessons" class="lessons-container">
      <h2>{{less.title}}</h2>

      <div class="lessons-grid">
   {% for lesson in course %}
<div class="lesson-card" data-lesson-id="{{ lesson.id }}">  <!-- <-- օգտագործում ենք lesson.id -->
    <h3>{{ lesson.title }}</h3>
    <p>{{ lesson.text }}</p>
    <button class="btn-view" onclick="showLesson(this)">
        {{ lesson.btn_text }}
    </button>
</div>
{% endfor %}

    </section>

    <div id="lesson-modal" class="modal">
      <div class="modal-content">
        <span class="close-btn" onclick="closeLesson()">&times;</span>
        <h2 id="modal-title"></h2>
        <div id="modal-body"></div>
        <a href="https://scratch.mit.edu/projects/editor/" target="_blank" class="btn-practice">Փորձել
          Scratch-ում</a>
      </div>
    </div>
  </main>
{% endblock  %}

 {% block scripts %}
<script>
const lessonsContent = JSON.parse(
    document.getElementById("lesson-data").textContent
);

const modal = document.getElementById("lesson-modal");
const modalTitle = document.getElementById("modal-title");
const modalBody = document.getElementById("modal-body");

function showLesson(btn) {
    const lessonId = btn.closest(".lesson-card").dataset.lessonId;
    const lesson = lessonsContent["1"];  //aystex petqa lini sa lessonId bayc qani vor im admin panelum sxal id sksvum dra hamar fix em dnum

    console.log(lesson); // հիմա title և content ԿԱՆ

    modalTitle.innerHTML = lesson.title;
    modalBody.innerHTML = lesson.content;
    modal.style.display = "block";
}

function closeLesson() {
    modal.style.display = "none";
}

window.onclick = function (event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}

</script>


  {% endblock  %}

quiz/templates/quiz/login.html
{% extends "base.html" %}
{% load static %}


{% block extra_css %}
  <link rel="stylesheet" href="{% static 'quiz/css/login.css' %}">
{% endblock %}

{% block content %}
<main>
    <div class="login-container">
             <div class="logo">

       <img class="img" src="{% static 'quiz/images/image1.png' %}" alt="">
         <h2>Մուտք Ձեր Էջ</h2> 
         <img class="text" src="{% static 'quiz/images/Scratchlogo.png' %}" alt="s">
    
    </div>
      

        <form id="login-form" method="POST">
    {% csrf_token %}
    <input type="email" id="email" name="email" placeholder="Էլ․հասցե" required>
    <input type="password" id="password" name="password" placeholder="Գաղտնաբառ" required>

    <button type="submit">Մուտք</button>

    <div class="forgot-password">
        <a href="{% url 'password_reset' %}">Մոռացել եք գաղտնաբառը՞</a>
    </div>

    {% if messages %}
        {% for message in messages %}
            <p style="color:red;">{{ message }}</p>
        {% endfor %}
    {% endif %}
</form>
    </div>
</main>
{% endblock  %}

quiz/templates/quiz/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'quiz/css/password_reset_complete.css' %}">
{% endblock %}

{% block content %}
<div class="success-wrapper">
    <div class="success-card">
        <div class="icon">✓</div>
        <h2>Գաղտնաբառը հաջողությամբ փոփոխվել է</h2>
        <p>Հիմա կարող եք մուտք գործել նոր գաղտնաբառով։</p>
        <a href="{% url 'login' %}" class="login-btn">Մուտք</a>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'quiz/css/forgot-password.css' %}" />
{% endblock %}

{% block content %}
<main>
  <div class="confirm-container">
    <div class="logo">
      <img class="img" src="{% static 'quiz/images/image1.png' %}" alt="" />
      <h2>Սահմանեք նոր գաղտնաբառ</h2>
      <img class="text" src="{% static 'quiz/images/Scratchlogo.png' %}" alt="logo" />
    </div>

    <form method="POST">
    {% csrf_token %}

    {{ form.new_password1.label_tag }}
    {{ form.new_password1 }}
    {{ form.new_password1.errors }}

    {{ form.new_password2.label_tag }}
    {{ form.new_password2 }}
    {{ form.new_password2.errors }}

    <button type="submit">
        Ապահովել նոր գաղտնաբառը
    </button>
</form>

  </div>
</main>
{% endblock %}

quiz/templates/quiz/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'quiz/css/password-done.css' %}">
{% endblock %}

{% block content %}
<div class="done-wrapper">
    <div class="done-card">
        <div class="icon">📩</div>
        <h2>Նամակը ուղարկված է</h2>
        <p>
            Եթե այդ email հասցեն գրանցված է համակարգում, 
            դուք շուտով կստանաք գաղտնաբառի վերականգնման հղում։
        </p>
        <a href="{% url 'login' %}" class="back-btn">
            Վերադառնալ մուտքի էջ
        </a>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/password_reset_email.html
Բարև,

Դուք խնդրել եք վերականգնել գաղտնաբառը։

Սեղմեք ստորև նշված հղումը՝

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Եթե դուք չեք պահանջել սա, պարզապես անտեսեք այս նամակը։

quiz/templates/quiz/register.html
{% extends "base.html" %}
{% load static %} 
 
 {% block extra_css %}
<link rel="stylesheet" href="{% static 'quiz/css/register.css' %}" />
{% endblock %}




{% block content %}
<main>
  <div class="register-container">
    <h2>Գրանցում</h2>
<form method="POST">
  {% csrf_token %}

  <div class="form-group">
    <label for="id_username" style="display:block; text-align:left;">Օգտվողի անուն</label>
    {{ form.username }}
    {{ form.username.errors }}
  </div>

  <div class="form-group">
    <label for="id_email" style="display:block; text-align:left;">Էլ․ հասցե</label>
    {{ form.email }}
    {{ form.email.errors }}
  </div>

  <div class="form-group" >
    <label for="id_age" style="display:block; text-align:left;">Տարիք</label>
    {{ form.age }}
    {{ form.age.errors }}
  </div>

  <div class="form-group">
    <label for="id_school" style="display:block; text-align:left;">Դպրոց / Դասարան</label>
    {{ form.school }}
    {{ form.school.errors }}
  </div>

  <div class="form-group">
    <label for="id_password1" style="display:block; text-align:left;">Գաղտնաբառ</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
  </div>

  <div class="form-group">
    <label for="id_password2" style="display:block; text-align:left;">Կրկնել գաղտնաբառը</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
  </div>

  <button type="submit">Գրանցվել</button>
</form>


    {% if messages %}
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    {% endif %}
  </div>
</main>
{% endblock %}